"""add index to published_at in interview_posts

Revision ID: 113d80f6884d
Revises: 3e36f6771974
Create Date: 2026-08-26 22:26:41.413591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113d80f6884d'
down_revision: Union[str, Sequence[str], None] = '3e36f6771974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_interview_posts_published_at'), 'interview_posts', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_posts_published_at'), table_name='interview_posts')
    # ### end Alembic commands ###
