"""add created_at to post_rounds

Revision ID: 3e36f6771974
Revises: b7b7f6f1ef19
Create Date: 2026-08-26 07:58:17.048123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e36f6771974'
down_revision: Union[str, Sequence[str], None] = 'b7b7f6f1ef19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_rounds', sa.Column('created_at', sa.DateTime(), nullable=False,  server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_rounds', 'created_at')
    # ### end Alembic commands ###
