"""add published_at and edit_count to interview_posts

Revision ID: 402ddc5d251d
Revises: 9f9c96aa35ca
Create Date: 2026-08-22 19:05:35.115556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402ddc5d251d'
down_revision: Union[str, Sequence[str], None] = '9f9c96aa35ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_posts', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('interview_posts', sa.Column('edit_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_posts', 'edit_count')
    op.drop_column('interview_posts', 'published_at')
    # ### end Alembic commands ###
